version: "3"
services:
  server:
    image: finall
    
    ports:
      - "8030:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/newbase?useSSL=false
    networks:
      - springboot-mysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=newbase
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234



networks:
  springboot-mysql-net: